server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            maxAge: 3600
      routes:
        - id: auth-public
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/login,/api/auth/forgot-password,/api/auth/reset-password,/api/auth/validate-token

        - id: auth-protected
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - name: JwtAuthFilter
              args: {}

        - id: cloud-profile-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/cloud/**
          filters:
            - name: JwtAuthFilter
              args: {}

        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/notifications/**
          metadata:
            response-timeout: 300000
            connect-timeout: 10000
          filters:
            - name: JwtAuthFilter
              args: {}

        - id: resource-management-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/resources/**
          filters:
            - name: JwtAuthFilter
              args: {}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG